kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cp4ba

bases:
  - ../../base

patchesStrategicMerge:
  - rr.yaml
  - ban.yaml
  - cpe.yaml
  - css.yaml
  - tm.yaml
  - ier.yaml
  - platform.yaml
  - ldap.yaml
  - patterns.yaml
  - components.yaml
  - graphql.yaml

patches:
  - target:
      kind: ICP4ACluster
      name: icp4adeploy
    # path: patch.yaml
    patch: |-
      - op: add
        path: "/spec/datasource_configuration/dc_os_datasources"
        value:
          - database_name: CP4BA
            database_port: "50000"
            database_servername: "c-db2-db2u.db2.svc.cluster.local"
            dc_common_os_datasource_name: FPOS
            dc_common_os_xa_datasource_name: FPOSXA
            dc_database_type: db2
            dc_os_label: fpos
          - database_name: CP4BA
            database_port: "50000"
            database_servername: "c-db2-db2u.db2.svc.cluster.local"
            dc_common_os_datasource_name: ROS
            dc_common_os_xa_datasource_name: ROSXA
            dc_database_type: db2
            dc_os_label: ros
          - database_name: CP4BA
            database_port: "50000"
            database_servername: "c-db2-db2u.db2.svc.cluster.local"
            dc_common_os_datasource_name: OS1
            dc_common_os_xa_datasource_name: OS1XA
            dc_database_type: db2
            dc_os_label: os1
      - op: add
        path: "/spec/initialize_configuration/ic_obj_store_creation/object_stores"
        value:
        - oc_cpe_obj_store_display_name: OS1
          oc_cpe_obj_store_symb_name: OS1
          oc_cpe_obj_store_conn:
            name: OS1_dbconnection
            dc_os_datasource_name: OS1
            dc_os_xa_datasource_name: OS1XA
          oc_cpe_obj_store_admin_user_groups:
            - cpadmin
            - cpadmins
          oc_cpe_obj_store_asa_name: os1_asa
          oc_cpe_obj_store_asa_file_systems_storage_device_name: os1_file_system_storage
          oc_cpe_obj_store_asa_root_dir_path: /opt/ibm/asa/os1_storagearea1
          oc_cpe_obj_store_enable_content_event_emitter: true
          oc_cpe_obj_store_addons_list:
            - "{CE460ADD-0000-0000-0000-000000000004}" # 5.2.1 Base Application Extensions (default)
            - "{CE460ADD-0000-0000-0000-000000000001}" # 5.2.1 Base Content Engine Extensions (default)
            - "{CE460ADD-0000-0000-0000-000000000003}" # (default)
            - "{CE511ADD-0000-0000-0000-000000000006}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000008}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000007}" # (default)
            - "{CE460ADD-0000-0000-0000-000000000009}" # (default)
            - "{CE460ADD-0000-0000-0000-00000000000A}" # (default)
            - "{CE460ADD-0000-0000-0000-00000000000B}" # (default)
            - "{CE460ADD-0000-0000-0000-00000000000D}" # (default)
            - "{CE511ADD-0000-0000-0000-00000000000F}" # (default)
            - "{CE511ADD-0000-0000-0000-000000000010}" # 5.2.1 Teamspace Extensions
            - "{CE511ADD-0000-0000-0000-000000000015}" # 5.2.1 Custom Role Extensions
            - "{CE521ADD-0000-0000-0000-000000000016}" # 5.2.1 Social Collaboration Role Extensions
            - "{CE552ADD-0000-0000-0000-00000000001C}" # 5.5.2 Core Collaboration Extensions
            - "{CE551ADD-0000-0000-0000-000000000011}" # 5.5.1 Social Collaboration Base Extensions
            - "{CE554ADD-0000-0000-0000-000000000021}" # 5.5.4 Event-Driven External Service Invocation Extensions
        - oc_cpe_obj_store_display_name: FPOS
          oc_cpe_obj_store_symb_name: FPOS
          oc_cpe_obj_store_conn:
            name: FPOS_dbconnection
            dc_os_datasource_name: FPOS
            dc_os_xa_datasource_name: FPOSXA
          oc_cpe_obj_store_admin_user_groups:
            - cpadmin
            - cpadmins
          oc_cpe_obj_store_asa_name: fpos_asa
          oc_cpe_obj_store_asa_file_systems_storage_device_name: fpos_file_system_storage
          oc_cpe_obj_store_asa_root_dir_path: /opt/ibm/asa/fpos_storagearea1
          oc_cpe_obj_store_enable_workflow: true
          oc_cpe_obj_store_workflow_region_name: fpos_region_name
          oc_cpe_obj_store_workflow_data_tbl_space: FPOS_TS
          oc_cpe_obj_store_workflow_admin_group: cpadmins
          oc_cpe_obj_store_workflow_config_group: cpadmins
          oc_cpe_obj_store_workflow_pe_conn_point_name: pe_conn_fpos
        - oc_cpe_obj_store_display_name: ROS
          oc_cpe_obj_store_symb_name: ROS
          oc_cpe_obj_store_conn:
            name: ROS_dbconnection
            dc_os_datasource_name: ROS
            dc_os_xa_datasource_name: ROSXA
          oc_cpe_obj_store_admin_user_groups:
            - cpadmin
            - cpadmins
          oc_cpe_obj_store_asa_name: ros_asa
          oc_cpe_obj_store_asa_file_systems_storage_device_name: ros_file_system_storage
          oc_cpe_obj_store_asa_root_dir_path: /opt/ibm/asa/ros_storagearea1
      - op: add
        path: "/spec/initialize_configuration/ic_icn_init_info/icn_repos"
        value:
          - add_repo_id: FPOS
            add_repo_os_sym_name: FPOS
            add_repo_os_dis_name: FPOS
          - add_repo_id: ROS
            add_repo_os_sym_name: ROS
            add_repo_os_dis_name: ROS
          - add_repo_id: OS1
            add_repo_os_sym_name: OS1
            add_repo_os_dis_name: OS1
      - op: add
        path: "/spec/initialize_configuration/ic_icn_init_info/icn_desktop"
        value:
          - add_desktop_id: ROS
            add_desktop_name: ROS
            add_desktop_description: ROS
            add_desktop_repo_id: ROS
          - add_desktop_id: OS1
            add_desktop_name: OS1
            add_desktop_description: OS1
            add_desktop_repo_id: OS1
      - op: add
        path: "/spec/verify_configuration/vc_icn_verification"
        value:
        - vc_icn_repository: ROS
          vc_icn_desktop_id: ROS   
        - vc_icn_repository: OS1
          vc_icn_desktop_id: OS1