apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
spec:
  appVersion: 22.0.1
  shared_configuration:
    sc_deployment_platform: "ROKS" 
    # sc_deployment_hostname_suffix not required. Please see: 
    # 1) https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=scp-shared-configuration
    # 2) https://www.ibm.com/docs/en/filenet-p8-platform/5.5.x?topic=operators-shared-parameters
    storage_configuration:
      sc_slow_file_storage_classname: "ibmc-file-gold-gid"
      sc_medium_file_storage_classname: "ibmc-file-gold-gid"
      sc_fast_file_storage_classname: "ibmc-file-gold-gid"
      sc_block_storage_classname: "ibmc-file-gold-gid"