apiVersion: icp4a.ibm.com/v1
kind: ICP4ACluster
metadata:
  name: icp4adeploy
  namespace: cp4ba
spec:
  ecm_configuration:
    tm:
      replica_count: 1
      tm_production_setting:
        # Based on https://www.ibm.com/docs/en/enterprise-records/5.2.1?topic=in-configuring-content-navigator-task-manager-enterprise-records
        # The publicly routable domain may not be needed. Can use the internal service construct instead, and it is created as part of the CR
        # process, but is instantiated well before the TM Deployment (about 45 mins before).
        tm_job_url: "https://ibm-nginx-svc.cp4ba.svc.cluster.local/ier/EnterpriseRecordsPlugin/IERApplicationPlugin.jar"
        security_roles_to_group_mapping:
          task_admins:
            groups: [cpadmins]
          task_users:
            groups: [cpusers]
          task_auditors:
            groups: [cpadmins]      
