{{- if .Values.existingSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap
  namespace: openldap
spec:
  data:
    - secretKey: adminPassword
      remoteRef:
        key: 91e35fb6-d1bd-87c2-09bd-0715322e7c11
    - secretKey: configPassword
      remoteRef:
        key: 74c4c648-c9c1-8a0a-3a71-1f3d2653acb9
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: openldap
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LDAP_ADMIN_PASSWORD: |-
          {{ "{{ .adminPassword | toString }}" }}
        LDAP_CONFIG_PASSWORD: |-
          {{ "{{ .configPassword | toString }}" }}
{{- end }}