# Default values for ltb-passwd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tiredofit/self-service-password
  tag: latest
  pullPolicy: Always
  pullSecrets: []


nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

## Configure Ingress based on the documentation here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  annotations: {}
  path: /
  ## Ingress Host
  # hosts:
  # - ssl-ldap.local
  #
  tls: []
  # tls:
  # - secretName: ssl-ldap-dedicated-tls
  #   hosts:
  #   - ssl-ldap.local
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
ldap:
  #searchBase: dc=example,dc=org
  # existingSecret: ssp-ldap
  #bindDN: cn=admin,dc=example,dc=org
  #bindPWKey: LDAP_ADMIN_PASSWORD
  custom:
    - name: TLS_REQCERT
      value: never
env:
- name: SECRETEKEY
  value: "password"
- name: LDAP_LOGIN_ATTRIBUTE
  value: "cn"
- name: LDAP_STARTTLS
  value: "false"
- name: CHANGE_SSHKEY
  value: "true"
  